spring:
  application:
    name: crm
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/crm}
    username: ${DATABASE_USERNAME:usr}
    password: ${DATABASE_PASSWORD:psw}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true